#!/usr/bin/env bash

sudo cp ide-handler.desktop /usr/share/applications
sudo update-desktop-database

sudo cp ide-handler /usr/bin/
sudo chmod +x /usr/bin/ide-handler

sudo cp starfish-1.0.0-SNAPSHOT-runner /usr/bin
sudo chmod +x /usr/bin/starfish

