#!/usr/bin/env bash

request=${1:22}



# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}
request="https://github.c"$request
echo $request
/usr/bin/starfish  $request
