#!/usr/bin/env bash

sudo cp ide-handler.desktop /usr/share/applications
sudo update-desktop-database

sudo cp ide-handler /usr/bin/
sudo chmod +x /usr/bin/ide-handler

sudo cp starfix /usr/bin
sudo chmod +x /usr/bin/starfix

