#!/usr/bin/env bash

# Delete first 22 characters (ide://open?url=file://)
request=${1:22}

# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}

# Launch Starfish
/usr/bin/starfish -g -r $request
