name: "Browser-Extension-Release-Chrome-Webstore"
on:
  push:
    branches:
      - master
    paths:
      - 'browser-extension/**'
  release:
    types: [created] 

jobs:
  chrome-extension:
    name: "zip-files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: browser-extension/
          dest: starfix-extension-chrome.zip
          
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: starfix-extension-chrome.zip
          path: ${{ github.workspace }}/starfix-extension-chrome.zip

      - name: "publish extension on chrome webstore"
        uses: Klemensas/chrome-extension-upload-action@master
        with:
          refresh-token: ${{ secrets.GOOGLE_CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.GOOGLE_CHROME_CLIENT_ID }}
          file-name: starfix-extension-chrome.zip
          app-id: 'ojlhpgekmmemhihkigibkhehlejkjdmo'
          publish: true

